services:
  seminarapi:
    container_name: seminarapi
    image: image_seminarapi
    build: .
    ports:
      - "127.0.0.1:8003:80"
    env_file:
      - .env
    networks:
      - my_network

networks:
  my_network:
    external: true
